openapi: 3.0.3
info:
  title: PMO  API
  version: v1
  description: PMO  Swagger Documentation
paths:
  /apiusers/{id}/:
    get:
      operationId: apiusers_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - apiusers
      security:
      - jwtAuth: []
      - JWT:
          type: http
          scheme: bearer
          bearerFormat: JWT
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /apiusers/login/:
    post:
      operationId: apiusers_login_create
      tags:
      - apiusers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - jwtAuth: []
      - JWT:
          type: http
          scheme: bearer
          bearerFormat: JWT
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
  /apiusers/refresh_token/:
    post:
      operationId: apiusers_refresh_token_create
      tags:
      - apiusers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshToken'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RefreshToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RefreshToken'
        required: true
      security:
      - jwtAuth: []
      - JWT:
          type: http
          scheme: bearer
          bearerFormat: JWT
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshToken'
          description: ''
  /apiusers/register/:
    post:
      operationId: apiusers_register_create
      tags:
      - apiusers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      - JWT:
          type: http
          scheme: bearer
          bearerFormat: JWT
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /apiusers/update-profile/:
    patch:
      operationId: apiusers_update_profile_partial_update
      tags:
      - apiusers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUpdateProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUpdateProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUpdateProfile'
      security:
      - jwtAuth: []
      - JWT:
          type: http
          scheme: bearer
          bearerFormat: JWT
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProfile'
          description: ''
components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access_token:
          type: string
          readOnly: true
        refresh_token:
          type: string
          readOnly: true
      required:
      - access_token
      - email
      - password
      - refresh_token
    PatchedUpdateProfile:
      type: object
      properties:
        email:
          type: string
          format: email
          nullable: true
          title: Email address
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        phone_number:
          type: string
          nullable: true
          maxLength: 50
        picture:
          type: string
          format: uri
          nullable: true
    RefreshToken:
      type: object
      properties:
        refresh_token:
          type: string
        access_token:
          type: string
          readOnly: true
      required:
      - access_token
      - refresh_token
    UpdateProfile:
      type: object
      properties:
        email:
          type: string
          format: email
          nullable: true
          title: Email address
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        phone_number:
          type: string
          nullable: true
          maxLength: 50
        picture:
          type: string
          format: uri
          nullable: true
    User:
      type: object
      properties:
        email:
          type: string
          format: email
          writeOnly: true
          nullable: true
          title: Email address
          maxLength: 254
        username:
          type: string
          writeOnly: true
          nullable: true
          maxLength: 150
        password:
          type: string
          writeOnly: true
          maxLength: 128
        refresh_token:
          type: string
          readOnly: true
        access_token:
          type: string
          readOnly: true
      required:
      - access_token
      - password
      - refresh_token
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
