# Generated by Django 5.2.5 on 2025-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_key_daftra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API KEY DAFTRA'),
        ),
        migrations.AddField(
            model_name='client',
            name='aws_access_key_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS Access Key ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='aws_s3_endpoint_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS S3 Endpoint URL'),
        ),
        migrations.AddField(
            model_name='client',
            name='aws_s3_region_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS S3 Region Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='aws_secret_access_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS Secret Access Key'),
        ),
        migrations.AddField(
            model_name='client',
            name='aws_storage_bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS Storage Bucket Name'),
        ),
    ]
