# Generated by Django 5.2.5 on 2025-08-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_client_api_key_daftra_client_aws_access_key_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='aws_access_key_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='aws_s3_endpoint_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='aws_s3_region_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='aws_secret_access_key',
        ),
        migrations.RemoveField(
            model_name='client',
            name='aws_storage_bucket_name',
        ),
    ]
