# Generated by Django 5.0 on 2025-11-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free Plan'), ('pro', 'Pro Plan'), ('max', 'Max Plan'), ('ultra', 'Ultra Plan')], max_length=50, unique=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('credits_per_month', models.PositiveIntegerField()),
                ('project_limit', models.CharField(max_length=50)),
                ('features', models.TextField()),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_per_month'],
            },
        ),
    ]
