# Generated by Django 5.0 on 2025-11-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
