# Generated by Django 5.0 on 2025-11-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeapp', '0002_subscription_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
