# Generated by Django 5.0 on 2025-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeapp', '0003_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='used_projects',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
