# Generated by Django 5.0 on 2025-11-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeapp', '0004_subscription_used_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.PositiveIntegerField(default=20, help_text='Cost in credits per stage')),
            ],
        ),
    ]
